<a href="https://colab.research.google.com/github/Cllasd44/Inteligencia-Artificiial/blob/main/PracticaSem10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NUMPY LIBRARY

In [ ]:
import numpy as np


In [3]:
print(np.__version__)

1.26.4


In [6]:
elArray=np.array([1,2,3,4,5])
print(elArray)

[1 2 3 4 5]


In [7]:
print(type(elArray))

<class 'numpy.ndarray'>


In [10]:
print(elArray.shape)
print(elArray[0])
print(elArray[1])
elArray[2]=8
print(elArray)

(5,)
1
2
[1 2 8 4 5]


In [11]:
elArray2=np.array([[1,2,3],[4,5,6]])
print(elArray2)
print(elArray2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [12]:
elArray3=np.zeros((5,5))
print(elArray3)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [13]:
elArray3=np.full((5,5),8)
print(elArray3)


[[8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]]


In [14]:
elArray3=np.eye(5)
print(elArray3)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [15]:
elArray3=np.ones((5,5))
print(elArray3)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [16]:
elArray3=np.random.random((5,5))
print(elArray3)

[[0.76327889 0.48246972 0.38609948 0.68361995 0.94703518]
 [0.17934735 0.2807657  0.01608796 0.22548485 0.92619119]
 [0.61397613 0.25817296 0.65822876 0.278803   0.43615772]
 [0.60764609 0.7029425  0.76063054 0.16802294 0.17311484]
 [0.05157194 0.42888055 0.75991007 0.06747177 0.64803264]]


In [17]:
alArray4=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(alArray4)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [18]:
elArray3=np.random.randint(10,size=6)
print(elArray3)

[8 8 5 1 4 5]


In [20]:
elArray3=np.random.randint(5,10,size=(6,6))
print(elArray3)

[[8 7 7 7 7 6]
 [7 9 5 9 8 8]
 [9 7 5 7 9 7]
 [6 8 8 5 9 5]
 [8 8 7 8 7 8]
 [9 8 9 8 7 8]]


In [21]:
laMatrix=elArray3[:2,1:3]
print(laMatrix)

[[7 7]
 [9 5]]


In [22]:
elArray3[1,2]=100
print(elArray3)

[[  8   7   7   7   7   6]
 [  7   9 100   9   8   8]
 [  9   7   5   7   9   7]
 [  6   8   8   5   9   5]
 [  8   8   7   8   7   8]
 [  9   8   9   8   7   8]]


In [23]:
print(elArray3[2,:])
print(elArray3[:,1])

[9 7 5 7 9 7]
[7 9 7 8 8 8]


In [27]:
print(elArray3[:,3].shape)

(6,)


In [28]:
print(elArray3[:,3:4].shape)

(6, 1)


In [29]:
print(elArray3[2:,3:4])

[[7]
 [5]
 [8]
 [8]]


In [30]:
unMatrix=elArray3[1:4,1:4]
print(unMatrix)

[[  9 100   9]
 [  7   5   7]
 [  8   8   5]]
