<a href="https://colab.research.google.com/github/Cllasd44/Inteligencia-Artificiial/blob/main/Semana12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
matrix1=np.array([[14,54,34,56],[12,23,56,34],[35,45,34,67]])
print(matrix1.shape)

(3, 4)


In [3]:
matrix1

array([[14, 54, 34, 56],
       [12, 23, 56, 34],
       [35, 45, 34, 67]])

In [4]:
print(matrix1[1:,1:3])

[[23 56]
 [45 34]]


In [6]:
# Create a 4x4 matrix with random integers between 0 and 9
matrix4x4 = np.random.randint(0, 10, size=(4, 4))
print(matrix4x4)
print(matrix4x4.shape)

[[0 6 0 3]
 [0 6 9 1]
 [0 2 3 4]
 [4 9 2 8]]
(4, 4)


In [7]:
print(matrix4x4)

[[0 6 0 3]
 [0 6 9 1]
 [0 2 3 4]
 [4 9 2 8]]


In [10]:
print(matrix4x4)
col_indices=np.array([1,3])
row_indices=np.array([0,2])
for row,col in zip(row_indices,col_indices):
    # print([row," ",col])
    print(matrix4x4[row,col])


[[0 6 0 3]
 [0 6 9 1]
 [0 2 3 4]
 [4 9 2 8]]
6
4


In [11]:
may=matrix4x4>7
print(may)

[[False False False False]
 [False False  True False]
 [False False False False]
 [False  True False  True]]


In [12]:
print(matrix4x4[may])

[9 9 8]


In [14]:
matrix4x4[matrix4x4 % 2== 0]+=100
print(matrix4x4)

[[100 106 100   3]
 [100 106   9   1]
 [100 102   3 104]
 [104   9 102 108]]


In [15]:
matrix4x4[(matrix4x4 >3) & (matrix4x4 < 9)]+=100
print(matrix4x4)

[[100 106 100   3]
 [100 106   9   1]
 [100 102   3 104]
 [104   9 102 108]]


In [16]:
matrix4x4[matrix4x4 % 2== 0]+=100
print(matrix4x4)

[[200 206 200   3]
 [200 206   9   1]
 [200 202   3 204]
 [204   9 202 208]]


In [17]:
matrix4x4[matrix4x4 % 2== 0]-=100
print(matrix4x4)

[[100 106 100   3]
 [100 106   9   1]
 [100 102   3 104]
 [104   9 102 108]]


In [18]:
matrix4x4[matrix4x4 % 2== 0]-=100
print(matrix4x4)

[[0 6 0 3]
 [0 6 9 1]
 [0 2 3 4]
 [4 9 2 8]]


In [19]:
matrixf=matrix4x4.flatten()
print(matrixf)

[0 6 0 3 0 6 9 1 0 2 3 4 4 9 2 8]


In [20]:
matrixf=matrix4x4.ravel()
print(matrixf)

[0 6 0 3 0 6 9 1 0 2 3 4 4 9 2 8]


In [22]:
matrixI1=np.random.randint(0,10,size=(3,3))
matrixI2=np.random.randint(0,10,size=(3,3))
print("Matrix1")
print(matrixI1)
print("Matrix2")
print(matrixI2)

Matrix1
[[7 4 0]
 [4 2 5]
 [7 8 9]]
Matrix2
[[7 9 9]
 [0 8 2]
 [5 5 9]]


In [23]:
print(matrixI1+matrixI2)
print(matrixI1-matrixI2)
print(matrixI1*matrixI2)
print(matrixI1/matrixI2)

[[14 13  9]
 [ 4 10  7]
 [12 13 18]]
[[ 0 -5 -9]
 [ 4 -6  3]
 [ 2  3  0]]
[[49 36  0]
 [ 0 16 10]
 [35 40 81]]
[[1.         0.44444444 0.        ]
 [       inf 0.25       2.5       ]
 [1.4        1.6        1.        ]]


<ipython-input-23-88e697e2451e>:4: RuntimeWarning: divide by zero encountered in divide
  print(matrixI1/matrixI2)


In [24]:
print(np.add(matrixI1,matrixI2))
print(np.subtract(matrixI1,matrixI2))
print(np.multiply(matrixI1,matrixI2))
print(np.divide(matrixI1,matrixI2))

[[14 13  9]
 [ 4 10  7]
 [12 13 18]]
[[ 0 -5 -9]
 [ 4 -6  3]
 [ 2  3  0]]
[[49 36  0]
 [ 0 16 10]
 [35 40 81]]
[[1.         0.44444444 0.        ]
 [       inf 0.25       2.5       ]
 [1.4        1.6        1.        ]]


<ipython-input-24-87a84fcfac42>:4: RuntimeWarning: divide by zero encountered in divide
  print(np.divide(matrixI1,matrixI2))


In [25]:
print(np.sqrt(matrixI1))

[[2.64575131 2.         0.        ]
 [2.         1.41421356 2.23606798]
 [2.64575131 2.82842712 3.        ]]


In [26]:
matrixI1=np.random.randint(0,10,size=(5,5))
print(matrixI1)

[[4 0 6 7 1]
 [0 5 1 0 8]
 [2 5 0 2 8]
 [3 2 2 2 3]
 [7 2 7 5 3]]


In [27]:
print(np.mean(matrixI1))
print(np.std(matrixI1))
print(np.var(matrixI1))

3.4
2.576819745345025
6.639999999999999


In [28]:
print(matrixI1.mean(axis=0))
print(matrixI1.mean(axis=1))

[3.2 2.8 3.2 3.2 4.6]
[3.6 2.8 3.4 2.4 4.8]


In [29]:
print(np.std(matrixI1,axis=0))
print(np.std(matrixI1,axis=1))

[2.31516738 1.93907194 2.78567766 2.48193473 2.87054002]
[2.72763634 3.18747549 2.8        0.48989795 2.03960781]


In [30]:
print(matrixI1.max(axis=0))
print(matrixI1.max(axis=1))

[7 5 7 7 8]
[7 8 8 3 7]


In [31]:
print(matrixI1.min(axis=0))
print(matrixI1.min(axis=1))

[0 0 0 0 1]
[0 0 0 2 2]


In [32]:
start=np.zeros((4,3))
print(start)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [33]:
add_rows=np.array([1,5,7])
print(add_rows)

[1 5 7]


In [34]:
add_rows=np.array([1,5,7])
print(add_rows.shape)

(3,)


In [35]:
y=start+add_rows
print(y)

[[1. 5. 7.]
 [1. 5. 7.]
 [1. 5. 7.]
 [1. 5. 7.]]


In [36]:
print(start)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [38]:
col_rows=np.array([1,5,7,6])
print(col_rows)

[1 5 7 6]


In [39]:
print(col_rows.T)

[1 5 7 6]


In [40]:
print(add_rows.T)

[1 5 7]


In [41]:
matrixT=start.T
print(matrixT)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [42]:
matrixT=start.T
print(matrixT)
print(start)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [43]:
matrixT=start+add_rows
print(matrixT)
print(start)

[[1. 5. 7.]
 [1. 5. 7.]
 [1. 5. 7.]
 [1. 5. 7.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [47]:
print(start)
top=col_rows.T
ed=start+top
print(ed)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [48]:
var1=array([[3,3],[5,5]])
var2=array([[4,3],[6,5]])
print(var1)
print(var2)

NameError: name 'array' is not defined

In [49]:
print(var1.dot(var2))

NameError: name 'var1' is not defined

In [50]:
var1=np.random.randint(low=2,high=50,size=(2,2))
var2=np.random.randint(low=2,high=50,size=(2,2))
print(var1)
print(var2)

[[44  4]
 [ 5 37]]
[[47 26]
 [28 33]]


In [51]:
np.vstack((var1,var2))

array([[44,  4],
       [ 5, 37],
       [47, 26],
       [28, 33]])

In [52]:
np.hstack((var1,var2))

array([[44,  4, 47, 26],
       [ 5, 37, 28, 33]])